// Angular build information, automatically generated by `4dams/angular-build-info`
export const buildInfo = {
    "user": "Juri Adams",
    "version": "1.0.0",
    "timestamp": "November 17, 2019 19:23:34"
}